// site/src/components/DynamicRange.svelte
<script lang="ts">
  type Mode = "light" | "dark";

  function getSurfaces(mode: Mode) {
    const isLight = mode === "light";
    return isLight
      ? [
          {
            name: "Page",
            className: "surface-page",
            label: "Start",
          },
          {
            name: "Card",
            className: "surface-card",
            label: "Mid",
          },
          {
            name: "Sidebar",
            className: "surface-workspace",
            label: "End",
          },
        ]
      : [
          {
            name: "Sidebar",
            className: "surface-workspace",
            label: "End",
          },
          {
            name: "Card",
            className: "surface-card",
            label: "Mid",
          },
          {
            name: "Page",
            className: "surface-page",
            label: "Start",
          },
        ];
  }
</script>

{#snippet rangeCard(title: string, description: string, mode: Mode)}
  {@const isLight = mode === "light"}
  {@const surfaces = getSurfaces(mode)}
  <div
    class="docs-card"
    style:color-scheme={mode}
    style:border="1px solid var(--border-subtle-token)"
    style:border-radius="8px"
    style:overflow="hidden"
    style:background="var(--surface-workspace)"
    style:box-shadow="var(--shadow-sm)"
  >
    <div
      style:padding="1rem"
      style:border-bottom="1px solid var(--border-subtle-token)"
    >
      <strong
        style:display="block"
        style:margin-bottom="0.5rem"
        style:color="var(--text-token)"
      >
        {title}
      </strong>
      <p
        style:margin="0"
        style:font-size="0.9em"
        style:color="var(--text-subtle-token)"
        style:line-height="1.4"
      >
        {description}
      </p>
    </div>

    <div
      class="surface-page"
      style:position="relative"
      style:height="220px"
      style:background="var(--surface-token)"
      style:color="var(--text-high-token)"
      style:padding="2rem"
    >
      <!-- Range Indicator Line -->
      <div
        style:position="absolute"
        style:left="1.5rem"
        style:top="2.5rem"
        style:bottom="2.5rem"
        style:width="4px"
        style:background="var(--border-dec-token)"
        style:border-radius="2px"
      ></div>

      <!-- Anchors Labels -->
      <div
        style:position="absolute"
        style:left="2.5rem"
        style:top="2rem"
        style:font-size="0.75em"
        style:font-weight="bold"
        style:color="var(--text-subtle-token)"
        style:font-family="var(--sl-font-mono)"
      >
        {isLight ? "Start" : "End"}
      </div>
      <div
        style:position="absolute"
        style:left="2.5rem"
        style:bottom="2rem"
        style:font-size="0.75em"
        style:font-weight="bold"
        style:color="var(--text-subtle-token)"
        style:font-family="var(--sl-font-mono)"
      >
        {isLight ? "End" : "Start"}
      </div>

      <!-- Stack Visualization -->
      <div
        style:margin-left="5rem"
        style:display="flex"
        style:flex-direction="column"
        style:height="100%"
        style:justify-content="space-between"
        style:gap="0.5rem"
      >
        {#each surfaces as s}
          <div
            class={s.className}
            style:background="var(--surface-token)"
            style:border="1px solid var(--border-dec-token)"
            style:border-radius="6px"
            style:padding="0 1rem"
            style:color="var(--text-high-token)"
            style:font-size="0.85em"
            style:font-weight="500"
            style:box-shadow="var(--shadow-sm)"
            style:display="flex"
            style:justify-content="space-between"
            style:align-items="center"
            style:flex="1"
          >
            <span>{s.name}</span>
            <span
              style:opacity="0.5"
              style:font-size="0.9em"
              style:font-family="var(--sl-font-mono)"
            >
              <!-- We don't have the exact L value available in CSS var -->
            </span>
          </div>
        {/each}
      </div>
    </div>
  </div>
{/snippet}

<div
  class="docs-grid docs-mb-4"
  style:display="grid"
  style:grid-template-columns="repeat(auto-fit, minmax(280px, 1fr))"
  style:gap="1.5rem"
  style:margin-top="1.5rem"
>
  {@render rangeCard(
    "Light Mode (Dimming)",
    "Page starts bright. Surfaces get darker to create separation.",
    "light"
  )}
  {@render rangeCard(
    "Dark Mode (Illumination)",
    "Page starts dark. Surfaces get lighter to approach the light source.",
    "dark"
  )}
</div>

// site/src/components/DynamicRange.tsx

export const DynamicRange = () => {
  return (
    <div className="docs-grid docs-mb-4" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1.5rem', marginTop: '1.5rem' }}>
      <RangeCard
        title="Light Mode (Dimming)"
        description="Page starts bright. Surfaces get darker to create separation."
        mode="light"
      />
      <RangeCard
        title="Dark Mode (Illumination)"
        description="Page starts dark. Surfaces get lighter to approach the light source."
        mode="dark"
      />
    </div>
  );
};

const RangeCard = ({ title, description, mode }: { title: string, description: string, mode: 'light' | 'dark' }) => {
  const isLight = mode === 'light';
  
  // Colors
  const borderColor = isLight ? 'var(--sl-color-gray-5)' : 'var(--sl-color-gray-5)';
  const textColor = isLight ? 'var(--sl-color-text)' : 'var(--sl-color-text)';
  const subtleColor = 'var(--sl-color-text-gray)';
  
  // Surfaces
  const surfaces = isLight 
    ? [
        { name: 'Page', l: '100%', color: '#ffffff', border: '#e5e5e5', text: '#000' },
        { name: 'Card', l: '95%', color: '#f5f5f5', border: '#e5e5e5', text: '#000' },
        { name: 'Sidebar', l: '90%', color: '#e5e5e5', border: '#d4d4d4', text: '#000' },
      ]
    : [
        { name: 'Sidebar', l: '25%', color: '#333333', border: '#444444', text: '#fff' },
        { name: 'Card', l: '18%', color: '#262626', border: '#404040', text: '#fff' },
        { name: 'Page', l: '10%', color: '#1a1a1a', border: '#333333', text: '#fff' },
      ];

  return (
    <div className="docs-card" style={{ 
      border: `1px solid ${borderColor}`, 
      borderRadius: '8px', 
      overflow: 'hidden', 
      background: 'var(--sl-color-bg-nav)',
      boxShadow: 'var(--sl-shadow-sm)'
    }}>
      <div style={{ padding: '1rem', borderBottom: `1px solid ${borderColor}` }}>
        <strong style={{ display: 'block', marginBottom: '0.5rem', color: textColor }}>{title}</strong>
        <p style={{ margin: 0, fontSize: '0.9em', color: subtleColor, lineHeight: 1.4 }}>{description}</p>
      </div>
      
      <div style={{ position: 'relative', height: '220px', background: isLight ? '#fafafa' : '#0a0a0a', padding: '2rem' }}>
        {/* Range Indicator Line */}
        <div style={{ 
          position: 'absolute', 
          left: '1.5rem', 
          top: '2.5rem', 
          bottom: '2.5rem', 
          width: '4px', 
          background: `linear-gradient(to bottom, ${surfaces[0].color}, ${surfaces[surfaces.length-1].color})`,
          borderRadius: '2px',
          border: `1px solid ${borderColor}`
        }} />

        {/* Anchors Labels */}
        <div style={{ position: 'absolute', left: '2.5rem', top: '2rem', fontSize: '0.75em', fontWeight: 'bold', color: subtleColor, fontFamily: 'var(--sl-font-mono)' }}>
          {isLight ? 'Start (100%)' : 'End (25%)'}
        </div>
        <div style={{ position: 'absolute', left: '2.5rem', bottom: '2rem', fontSize: '0.75em', fontWeight: 'bold', color: subtleColor, fontFamily: 'var(--sl-font-mono)' }}>
          {isLight ? 'End (90%)' : 'Start (10%)'}
        </div>

        {/* Stack Visualization */}
        <div style={{ 
          marginLeft: '5rem', 
          display: 'flex', 
          flexDirection: 'column', 
          height: '100%', 
          justifyContent: 'space-between',
          gap: '0.5rem'
        }}>
          {surfaces.map((s, i) => (
            <div key={i} style={{
              background: s.color,
              border: `1px solid ${s.border}`,
              borderRadius: '6px',
              padding: '0 1rem',
              color: s.text,
              fontSize: '0.85em',
              fontWeight: 500,
              boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              flex: 1
            }}>
              <span>{s.name}</span>
              <span style={{ opacity: 0.5, fontSize: '0.9em', fontFamily: 'var(--sl-font-mono)' }}>{s.l}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
